spring:
  influxdb:
    url: http://localhost:8086
    username: admin
    password: 123456
    database: testdb
    retention-policy: default

#opc配置
opc:
  kep:
    _host: 127.0.0.1    #电脑IP
    _domain:             #域，为空就行
    _user: OPCUser       #电脑上自己建好的用户名
    _password: 123456    #密码
    _clsid: 7BC0CC8E-482C-47CA-ABDC-0FE7F9C6E729 #使用KEPServer的配置
    prefix: 通道 3.设备 1.TAG  #标记前缀

logging:
  level:
    org.jinterop : off
  file:
    path: ./
    name: xiaoxing.log
    max-history: 2